sources:
  - name: jaffle_shop
    database: smart-amplifier-464317-c0
    schema: jaffle_shop
    tables:
      - name: customers
      - name: orders
      - name: items
      - name: products
      - name: suppliers
